@BaseUrl = http://localhost:5114
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwic3RhdHVzIjoiQWN0aXZlIiwianRpIjoiYzExMmViNmYtM2U2Ny00ZTdlLWIyNmEtMTc0ZTFkNDhkNjlhIiwiZXhwIjoxNzUwNDgyNzQzLCJpc3MiOiJZb3VyQXBwIiwiYXVkIjoiWW91ckFwcEF1ZGllbmNlIn0.5Id_Ag7dKxeccEF9zBXSz_AvHAvYChQeQgHJZfYH6bY

### Login
POST {{BaseUrl}}/api/users/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "123"
}

### Register / Create new user
POST {{BaseUrl}}/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "phoneNumber": "08123456789",
  "passwordHash": "123"
}

### GET Me
GET {{BaseUrl}}/api/users/me
Accept: application/json
Authorization: Bearer {{Token}}

### GET all users
GET {{BaseUrl}}/api/users
Accept: application/json
Authorization: Bearer {{Token}}

### GET user by ID
GET {{BaseUrl}}/api/users/1
Accept: application/json
Authorization: Bearer {{Token}}

### UPDATE user by ID
PUT {{BaseUrl}}/api/users/1
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "name": "John D.J",
  "email": "john.edit@example.com",
  "phoneNumber": "081239999",
  "status": "Inactive"
}

### DELETE user by ID
DELETE {{BaseUrl}}/api/users/1
Authorization: Bearer {{Token}}

